/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface AppGeneratorOptions {
  /**
   * The directory of the new application.
   */
  directory: string;
  /**
   * Add tags to the application.
   */
  tags?: string;
  /**
   * The name of the application.
   */
  name: string;
  /**
   * Create node application at the root of the workspace
   */
  rootProject?: boolean;
  /**
   * Add a docker build target
   */
  docker?: boolean;
  [k: string]: unknown;
}
