changesetIgnorePatterns:
  - .github/**
  - .yarn/cache/**
  - "**/*.spec.{js,ts}"
  - "**/*.test.{js,ts}"

compressionLevel: mixed

enableGlobalCache: false

enableMirror: false

enableTelemetry: false

logFilters:
  - code: YN0002
    level: discard

nodeLinker: node-modules

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.3.1.cjs
