/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Options to use with cdktf deploy
 */
export interface DeployExecutorOptions {
  postTargets?: string[];
  /**
   * Command to use in order to execute cdktf app
   */
  app?: string;
  /**
   * Output directory for the synthesized Terraform config
   */
  output?: string;
  /**
   * Auto approve
   */
  autoApprove?: boolean;
  /**
   * Path to file where stack outputs will be written as JSON
   */
  outputsFile?: string;
  /**
   * Whether to include sensitive outputs in the output file
   */
  outputsFileIncludeSensitiveOutputs?: boolean;
  /**
   * Don't check if all stacks specified in the command have their dependencies included as well
   */
  ignoreMissingStackDependencies?: boolean;
  /**
   * Number of concurrent CDKTF stacks to run. Defaults to infinity, denoted by -1
   */
  parallelism?: number;
  /**
   * Select the "refresh only" planning mode, which checks whether remote objects still match the outcome of the most recent Terraform apply but does not propose any actions to undo any changes made outside of Terraform.
   */
  refreshOnly?: boolean;
  /**
   * Forwards value as the `-parallelism` flag to Terraform. By default, the this flag is not forwarded to Terraform. Note: This flag is not supported by remote / cloud backend
   */
  terraformParallelism?: number;
  /**
   * Disables terminal formatting sequences in the output.
   */
  noColor?: boolean;
  /**
   * Pass this flag after switching state backends to approve a state migration for all targeted stacks
   */
  migrateState?: boolean;
  /**
   * Set a value for one of the input variables in the stack or stacks to apply. Use this option more than once to set more than one variable.
   */
  var?: string[];
  /**
   * Load variable values from the given file, in addition to the default files terraform.tfvars and *.auto.tfvars. Use this option more than once to include more than one variables file.
   */
  varFile?: string[];
  /**
   * Skip synthesis of the application, assume the synthesized Terraform code is already present and up to date
   */
  skipSynth?: boolean;
  /**
   * List of stacks to deploy
   */
  stacks?: string[];
}
