/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Options to use with cdktf synth
 */
export interface SynthExecutorOptions {
  postTargets?: string[];
  /**
   * Command to use in order to execute cdktf app
   */
  app?: string;
  /**
   * Output directory for the synthesized Terraform config
   */
  output?: string;
  /**
   * Should `codeMakerOutput` existence check be performed? By default it will be checked if providers or modules are configured.
   */
  checkCodeMakerOutput?: boolean;
  /**
   * Should the output be in HCL format?
   */
  hcl?: string;
  /**
   * List of stacks to deploy
   */
  stacks?: string[];
}
