name: Publish

on:
  workflow_dispatch:
    inputs:
      projectName:
        type: string
        description: Name of project to publish
        required: true

concurrency:
  group: ${{ format('{0}-{1}-{2}', github.workflow, github.job, github.event.ref) }}
  cancel-in-progress: false

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      NPM_CONFIG_PROVENANCE: true
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "yarn.lock"
          scope: "plastic-ant"
          registry-url: https://registry.npmjs.org/

      - name: Install Dependencies
        run: SKIP_POSTINSTALL=1 yarn

      - uses: nrwl/nx-set-shas@v4

      - name: Build
        run: yarn exec nx affected --nx-bail --target=build --parallel --configuration=ci --head=${{ env.NX_HEAD }} --base=${{ env.NX_BASE }}

      - name: Publish packages
        run: yarn exec nx release --projects=${{ github.event.inputs.projectName }} --first-release --dry-run

      - name: Push
        run: |
          git push
          git push --tags
