name: Tests

on:
  push:

concurrency:
  group: ${{ format('{0}-{1}-{2}', github.workflow, github.job, github.event.ref) }}
  cancel-in-progress: true

jobs:
  Tests:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - run: yarn install --immutable

      - run: yarn npm audit -R -A --severity high

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx affected -t test,lint,build --configuration=ci
