name: Tests

on:
  push:

concurrency:
  group: ${{ format('{0}-{1}-{2}', github.workflow, github.job, github.event.ref) }}
  cancel-in-progress: true

jobs:
  Tests:
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: "pnpm-lock.yaml"

      - run: pnpm install --frozen-lockfile

      # - run: pnpm audit

      - uses: nrwl/nx-set-shas@v4

      - run: pnpm exec nx affected -t test,lint,build --configuration=ci --verbose --nxBail
