name: Version

on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: The version to use for the release.
        default: ""
      dry-run:
        type: boolean
        description: Dry run nx release
        default: true
  push:
    branches:
      - "main"

concurrency:
  group: ${{ format('{0}-{1}-{2}', github.workflow, github.job, github.event.ref) }}
  cancel-in-progress: false

jobs:
  Version:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - run: yarn install --immutable

      - uses: nrwl/nx-set-shas@v4

      - run: npx nx release version --dry-run=${{ env.DRY_RUN }} ${{ env.VERSION }}
        env:
          DRY_RUN: ${{ github.event_name == 'workflow_dispatch' && inputs.dry-run }}
          VERSION: ${{ github.event_name == 'push' && '' || inputs.version }}
          NX_VERBOSE_LOGGING: ${{ runner.debug && true || false }}
