name: Version

on:
  push:
    branches:
      - main

concurrency:
  group: ${{ format('{0}-{1}-{2}', github.workflow, github.job, github.event.ref) }}
  cancel-in-progress: false

jobs:
  publish:
    name: Version
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          cache-dependency-path: "yarn.lock"

      - name: Install Dependencies
        run: SKIP_POSTINSTALL=1 yarn

      - uses: nrwl/nx-set-shas@v4

      - name: Version Packages
        run: yarn exec nx release version

      - name: Push
        run: |
          git push
          git push --tags
