services:
  repo:
    build:
      context: ../
      dockerfile: ../.devcontainer/packages/dockerfile
      args:
        NODE_VARIANT: 20
    volumes:
      - ${HOME}${USERPROFILE}/.ssh:/home/node/.ssh:ro
      - ../..:/pas-packages:cached
    command: sleep infinity
